name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  myProfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install packages
        run: npm install
      # - name: Test React
      #   env:
      #     CI: true
      #   run: npm test
      - name: Build React
        run: npm run build
      - name: Deploy Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: profile
          publish_dir: ./build